services:
  masto-rss:
    # Use the pre-built image from Docker Hub
    image: doorknob2947/masto-rss-advanced:latest
    container_name: masto-rss-bot
    restart: unless-stopped
    volumes:
      # This volume persists the history of posted links
      - ./state:/state
    environment:
      # --- Mastodon API Credentials (Required) ---
      - MASTODON_CLIENT_ID=YOUR_CLIENT_KEY_HERE
      - MASTODON_CLIENT_SECRET=YOUR_CLIENT_SECRET_HERE
      - MASTODON_ACCESS_TOKEN=YOUR_ACCESS_TOKEN_HERE
      - MASTODON_INSTANCE_URL=[https://mastodon.social](https://mastodon.social)

      # --- RSS Feed Configuration (Required) ---
      - RSS_FEED_URL=[https://www.theverge.com/rss/index.xml](https://www.theverge.com/rss/index.xml)

      # --- Bot Behavior (Optional) ---
      - CHECK_INTERVAL=3600 # Time in seconds between checks (e.g., 1 hour)
      - MAX_HISTORY_SIZE=500 # Max number of posted links to remember
      - TOOT_VISIBILITY=public # public, unlisted, private, or direct

      # --- Toot Content (Optional) ---
      - MASTO_RSS_HASHTAGS="news tech python" # Space-separated list of hashtags
      - TOOT_TEMPLATE='{title}\n\n{link}\n\n{hashtags}'

      # --- System (Do not change) ---
      - PYTHONUNBUFFERED=1
